# This Build Strategy will intentionally fail if the image has any
# critical CVEs. It will not be pushed into the destination registry
# if any critical vulnerabilities are found.
---
apiVersion: shipwright.io/v1alpha1
kind: ClusterBuildStrategy
metadata:
  name: kaniko-trivy
spec:
  buildSteps:
    - name: kaniko-build
      image: gcr.io/kaniko-project/executor:v1.6.0
      workingDir: $(params.shp-source-root)
      securityContext:
        runAsUser: 0
        capabilities:
          add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            - SETFCAP
            - KILL
      env:
        - name: HOME
          value: /tekton/home
        - name: AWS_ACCESS_KEY_ID
          value: NOT_SET
        - name: AWS_SECRET_KEY
          value: NOT_SET
      command:
        - /kaniko/executor
      args:
        - --skip-tls-verify=true
        - --dockerfile=$(build.dockerfile)
        - --context=$(params.shp-source-context)
        - --destination=$(params.shp-output-image)
        - --oci-layout-path=/kaniko/oci-image-layout
        - --snapshotMode=redo
        - --no-push
        - --tarPath
        - /tar/image.tar
      volumeMounts:
        - name: tar
          mountPath: /tar/
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
    # Reference:
    # https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-advanced-2/devsecops-trivy/
    - name: trivy-scan
      image: aquasec/trivy:0.19.2
      volumeMounts:
      - mountPath: /image/
        name: tar
      command:
        - trivy
      args:
        - --quiet
        - --exit-code=1
        - --severity=CRITICAL
        - --input
        - /image/image.tar
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi

    # Reference:
    # https://ibm-gsi-ecosystem.github.io/ibm-gsi-cloudnative-journey/developer-advanced-2/devsecops-trivy/
    - name: crane-push
      image: gcr.io/go-containerregistry/crane:v0.6.0
      # Needed to read the docker config
      securityContext:
        runAsUser: 0
      volumeMounts:
      - mountPath: /image/
        name: tar
      command:
        - crane
      args:
        - push
        - /image/image.tar
        - $(build.output.image)
      env:
        - name: DOCKER_CONFIG
          value: /root/.docker/
