apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s2i-builders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitserver.git/applications.git
    targetRevision: master
    path: applications/s2i-builders
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
